apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-front-deployment
  labels:
    app.kubernetes.io/name: todo-list
    app.kubernetes.io/component: deployment
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-list
      app.kubernetes.io/component: webapp
      tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-list
        app.kubernetes.io/component: webapp
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: quay.io/yborgess/todo-list-react-frontend
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ENV_BACKEND_SVC_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENV_BACKEND_SVC_NAME
              value: "todo-list-backend-svc"
            - name: ENV_BACKEND_HOST
              value: "http://$(ENV_BACKEND_SVC_NAME).$(ENV_BACKEND_SVC_NS).svc.cluster.local"
          volumeMounts:
            - mountPath: /var/run
              name: tmpfs-1
            - mountPath: /var/cache/nginx
              name: tmpfs-2
            - mountPath: /etc/nginx/conf.d
              name: tmpfs-3
            - mountPath: /var/log/nginx
              name: tmpfs-4
      volumes:
        - name: tmpfs-1
          emptyDir: { }
        - name: tmpfs-2
          emptyDir: { }
        - name: tmpfs-3
          emptyDir: { }
        - name: tmpfs-4
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: todo-list-frontend-svc
  labels:
    app.kubernetes.io/name: todo-list
    app.kubernetes.io/component: service
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: todo-list
    app.kubernetes.io/component: webapp
    tier: frontend

